In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,2],[3,4]])
m1

array([[1, 2],
       [3, 4]])

In [5]:
np.cos(m1)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [8]:
m2 = np.array([[5,6],[7,8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [9]:
v1 = np.array([1,2])
m1+v1

array([[2, 4],
       [4, 6]])

In [11]:
m23 = np.array([[1,2,3],[4,5,6]])
m23

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
m23.size, m23.ndim, m23.shape

(6, 2, (2, 3))

In [19]:
v12 = np.arange(12)
v12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
m34 = v12.reshape(3,-1)
m34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
m43 = v12.reshape(-1,3)
m43

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
v12.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
m1.reshape(1,-1)

array([[1, 2, 3, 4]])

In [31]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [32]:
m1010 = np.arange(100).reshape(10,10)
m1010

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
m1010[1:-1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [36]:
m1010[3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
m1010[3,2]

np.int64(32)

In [38]:
m1010[2:8,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76]])

In [40]:
m1010[2:8,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [41]:
m1010[:,3:7]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76],
       [83, 84, 85, 86],
       [93, 94, 95, 96]])

In [42]:
m1010[8:2:-1,7:3:-2]

array([[87, 85],
       [77, 75],
       [67, 65],
       [57, 55],
       [47, 45],
       [37, 35]])

In [44]:
m1010[[2,5],[7,6]]

array([27, 56])

In [45]:
m1

array([[1, 2],
       [3, 4]])

In [47]:
for row in m1:
    for col in row:
        print(col)

1
2
3
4
