In [1]:
import numpy as np

In [13]:
# np.random.seed(42)
rnd1 = np.random.rand(10) * 2
rnd1

array([1.22370579, 0.27898772, 0.5842893 , 0.73272369, 0.91213997,
       1.57035192, 0.39934756, 1.02846888, 1.18482914, 0.09290083])

In [9]:
rnd2 = np.random.randint(0,100,10)
rnd2

array([21, 52,  1, 87, 29, 37,  1, 63, 59, 20], dtype=int32)

In [14]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [17]:
result = np.sin(a1)
result

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
for i in a1:
    print(i)

1
2
3
4


In [19]:
np.max(a1)

np.int64(4)

In [20]:
print(a1.ndim, a1.size, a1.shape, a1.dtype)

1 4 (4,) int64


In [22]:
a10 = np.arange(100,110)
a10

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [23]:
for v in a10:
    print(v)

100
101
102
103
104
105
106
107
108
109


In [24]:
a10[0]

np.int64(100)

In [26]:
for i in np.arange(len(a10)):
    print(a10[i])

100
101
102
103
104
105
106
107
108
109


In [28]:
a10[-2]

np.int64(108)

In [29]:
a10[2:6]

array([102, 103, 104, 105])

In [33]:
n=3
a10[n:-n]

array([103, 104, 105, 106])

In [34]:
a10[-3:-1]

array([107, 108])

In [35]:
a10[-3:]

array([107, 108, 109])

In [36]:
a10[:3]

array([100, 101, 102])

In [37]:
a10[:]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [38]:
a10[1:-1:2]

array([101, 103, 105, 107])

In [39]:
a10[::2]

array([100, 102, 104, 106, 108])

In [45]:
np.flip(a10[::-3])

array([100, 103, 106, 109])