In [1]:
import numpy as np

In [2]:
mat33 = np.arange(9).reshape(3,3)
mat33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.sum(mat33)

np.int64(36)

In [4]:
np.sum(mat33, axis=0)

array([ 9, 12, 15])

In [5]:
np.sum(mat33, axis=1)

array([ 3, 12, 21])